### ISSUE TITLE
Facebook API updated

### ISSUE THREAD

**Issue by fractalfederation** [Centillien/elgg_social_login#3]
Installed latest on GitHub and get the following error with Facebook:

Invalid Scopes: offline_access, publish_stream, read_friendlists. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Appears Facebook updated their API and deprecated publish_stream. HybridAuth may have updated it on their end. I tried just dropping in the latest HybridAuth to see if that would work, it didn't.

Can you push your latest version?

Thanks,
Blake

**Comment by fractalfederation** [comment]
I've removed the deprecated scopes from vendors/hybridauth/Hybrid/Providers/Facebook.php and can connect using Facebook now. I also looked at the latest HybridAuth version of that file and added the new scopes but I don't think your plugin is even using them so, idk.

**Comment by gerard-kanters** [comment]
You are right, I have removed them from the public scope as well. The plugin is not doing anything with these scopes
