### ISSUE TITLE
FB Auth error

### ISSUE THREAD

**Issue by Yaco** [Centillien/elgg_social_login#4]
Hi!
I am trying to connect using FB. I couldn't find how to define the callback URL. I am getting the following error:

```
Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions
```

Thanks!

**Comment by gerard-kanters** [comment]
Hi Yaco,

I am not really supporting this plugin anymore, but you can fix it by changing the public scope here

https://github.com/Centillien/elgg_social_login/blob/master/vendors/hybridauth/Hybrid/Providers/Facebook.php#L18 

Remove read_stream from the scope.
